apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-agent
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-agent
  template:
    metadata:
      labels:
        app: jenkins-agent
    spec:
      containers:
      - name: jenkins-agent
        image: ihebrj/jenkins-agent:latest
        env:
        - name: JENKINS_URL
          value: "http://jenkins-service:8080"  # Use the Jenkins service from the current namespace
        - name: JENKINS_AGENT_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: JENKINS_SECRET
          value: "<provided_secret> "  # Agent secret from Jenkins UI / put your provided value
        - name: JENKINS_AGENT_WORKDIR
          value: "/home/jenkins"  # Define the working directory for the agent
        volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
      volumes:
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
          type: Socket
